- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: checking does user exits or not
    ansible.builtin.command: id roboshop
    register: user # user is a variable name
    ignore_errors: true
    
  - name: print variable name
    ansible.builtin.debug:
      msg: "user output is :{{user}}"
  
  
