- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: checking does user exits or not
    ansible.builtin.command: id roboshop
    register: user # user is a variable name
    ignore_errors: true

  - name: print variable name
    ansible.builtin.debug:
      msg: "user output is :{{user}}"
  - name: print exits status
    ansible.builtin.debug:
      msg: "user status is : {{user.rc}}"
  

  - name: creating user
    ansible.builtin.user:
     name: roboshop
    when : user.rc != 0 # run the condition
  
  
