- name: conditions
  hosts: localhost
  become: yes
  tasks:
  - name: checking does user exits or not
    ansible.built.command: id roboshop
    register: user # user is a variable name

  - name: print variable name
    ansible.built.debug:
    msg: "user output is :{{user}}"
  
  
